# Obtain JWT Token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###

# Use JWT Token
GET http://127.0.0.1:8000/students/student/673d5b2e792b74d3d11a1575/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzYxOTE4LCJpYXQiOjE3MzI3NjE2MTgsImp0aSI6ImNlNWE5Y2YyZWJmYTQzZmI4MzFkNTA3NjQyMWY5ZmU4IiwidXNlcl9pZCI6MX0.ajnRjhyl-1XgIghgdlg-A4t0wVQM-uEW7Pf2E08RDmM

###

# Test POST Request
POST http://127.0.0.1:8000/students/student/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzYwOTAwLCJpYXQiOjE3MzI3NjA2MDAsImp0aSI6IjhhYmYxYTIwNWQyYjQ3Njk5MTMxZjUzMTIzNzFiN2ZjIiwidXNlcl9pZCI6MX0.sl8vPIas6LYIv55BmQ-20RPOQkHffTNY9FVZg4yiOtA

{
    "name": "Haris Rosdi",
    "age": 23,
    "course": "Computer Networks"
}

###

# Test PUT Request
PUT http://127.0.0.1:8000/students/student/67454973d95c6cb089c881de/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzYxNDg5LCJpYXQiOjE3MzI3NjExODksImp0aSI6IjY5NTk4NWU4MWYzMDQ3NzI4ZGEzODEzOTdmODM4YjA2IiwidXNlcl9pZCI6MX0.50ScL8hXhWbDgNP4jvy2WWjBed7FMbirwA5ZnB3O0eY

{
    "student_id": 5,
    "name": "Haziq Khalis",
    "age": 22,
    "course": "Computer Networks"
}

###

# Test PATCH Request
PATCH http://127.0.0.1:8000/students/student/674548d0d95c6cb089c881dd/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyNzYxNDg5LCJpYXQiOjE3MzI3NjExODksImp0aSI6IjY5NTk4NWU4MWYzMDQ3NzI4ZGEzODEzOTdmODM4YjA2IiwidXNlcl9pZCI6MX0.50ScL8hXhWbDgNP4jvy2WWjBed7FMbirwA5ZnB3O0eY

{
    "course": "Computer Networks"
}

###

# Test DELETE Request
DELETE http://127.0.0.1:8000/students/student/1/
Authorization: Bearer <your-jwt-token>